--create table dealtracker (
--       id bigint auto_increment,
--       dealReference varchar(32),
--       chain varchar(2),
--       chainNumber int,
--       arrivalTime timestamp,
--       sentTime timestamp,
--       vestCompleteTime timestamp,
--       appCompleteTime timestamp,
--       primary key (id)
--    );